# Remove build artifacts
@clean:
    echo "{{BLUE}}Removing host build artifacts...{{NORMAL}}"
    cargo clean

# Format and lint
@check:
    echo "{{BLUE}}Formatting and linting host...{{NORMAL}}"
    cargo +nightly fmt --all
    cargo +nightly clippy --workspace --all-features -- -D warnings

# Sort dependencies
@sort:
    echo "{{BLUE}}Sorting host dependencies...{{NORMAL}}"
    cargo sort -g

# Update dependencies
@update:
    echo "{{BLUE}}Updating host dependencies...{{NORMAL}}"
    cargo update

# Check for outdated  dependencies
@outdated:
    echo "{{BLUE}}Checking for outdated host dependencies...{{NORMAL}}"
    cargo outdated -R

# Debug build
@debug:
    echo "{{BLUE}}Building host in debug mode...{{NORMAL}}"
    cargo build

# Release  build
@release:
    echo "{{BLUE}}Building  host in release mode...{{NORMAL}}"
    cargo build --release